### ISSUE TITLE
After logging in user is not redirected back to SharePoint site

### ISSUE THREAD

**Issue by Codefearingguy** [MicrosoftDocs/OfficeDocs-Enterprise#101]
I have followed through all the steps and when I try to access my SharePoint site, I get redirected to login.microsoftonline.com, but then it goes into continous loop in this url:
https://login.microsoftonline.com/{objectid}/wsfed?wa=wsignin1.0&wtrealm=urn%3as509lab&wctx=https%3a%2f%2fs509lab%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F

Below is my environment set up:

- SharePoint 2013 
- Used self signed certificates
- Saml1.1 policy is applied and verfied using Azure AD graph explorer tool. 
- Token issuer is also checked and is configured correctly. 
- Azure AD app has correct reply url specified

Any ideas?

**Comment by Codefearingguy** [comment]
Tried with "/_trust/" &  /_trust/default.aspx still the same behaviour. Goes on a loop in the https://login.microsoftonline.com/{objectid}/wsfed?wa=wsignin1.0&wtrealm=urn%3as509lab&wctx=https%3a%2f%2fs509lab%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F url

**Comment by kaevans** [comment]
Another trick to try is to open a private browsing session (In Private or Incognito) as there could be an issue with an existing cookie in your environment. Using a private browsing session opens a new session without reading existing cookies, forcing you to go through the entire logon sequence.

Here is a summary of the traffic in my environment (captured using Fiddler) during a private browsing session. Perhaps monitoring the traffic and comparing against expected results might give an indication of what is happening in your environment.

1) Go to SharePoint site, causes a 302 redirect to https://portal.contoso.local/_trust/?ReturnUrl=%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F&Source=%2F
2) That causes a 302 redirect to https://portal.contoso.local/_trust/?ReturnUrl=%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F&Source=%2F
3) That causes a 302 redirect to https://login.microsoftonline.com/b1726649-b616-460d-8d20-defab80d476c/wsfed?wa=wsignin1.0&wtrealm=urn%3asharepoint%3aportal.contoso.local&wctx=https%3a%2f%2fportal.contoso.local%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252F&wreply=https%3a%2f%2fportal.contoso.local%2f_trust%2fdefault.aspx.
4) Redirected to ADFS. I log into ADFS, which then does an HTTP post to AAD at https://login.microsoftonline.com/login.srf. 
5) I get a dialog for "keep me signed in", which causes a POST to https://login.microsoftonline.com/kmsi. 
6) That causes a 302 redirect to https://portal.contoso.local/_trust/default.aspx
7) That causes a 302 redirect to https://portal.contoso.local/_layouts/15/Authenticate.aspx?Source=%2F
8) That causes a 302 redirect to https://portal.contoso.local/
9) Finally redirected to https://portal.contoso.local/_layouts/15/start.aspx

Step 3 is slightly different in my environment because I am using the wreply parameter due to having the trusted provider registered to multiple web applications. Two things you might do are to monitor the HTTP traffic to identify what is the thing that is redirecting to that URL, and watch the SharePoint ULS logs to see if there is any indication of what is going wrong.
