### ISSUE TITLE
Group Claims

### ISSUE THREAD

**Issue by SashaSidorenko** [MicrosoftDocs/OfficeDocs-Enterprise#109]
Could you please add the instructions how to add Azure AD group claims to SharePoint trusted identity token issuer. It will be very helpful to use Azure AD groups to share something on SharePoint On-Premises

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
@SashaSidorenko Azure AD will not include O365 groups as part of the token that is posted to the SharePoint STS. Instead, a custom claims provider is needed to augment the user claims to include groups they are a member of.  One example of this is https://blogs.msdn.microsoft.com/jesusfer/2016/01/25/sharepoint-2013-role-claims-augmentation/. AzureCP should enable this as well via Graph API lookups. Details on custom claims providers and performing claims augmentation or instructions on configuring AzureCP is outside the scope of the article.

**Comment by SashaSidorenko** [comment]
Adding possibility to share data with O365 groups can be managed by adding http://schemas.microsoft.com/ws/2008/06/identity/claims/groups claim mapping to SharePoint server TrustedIdentityTokenIssuer and enabling groupMembershipClaims "SecurityGroup" in AAD App Registration manifest. After that, you can ensure groups in PeoplePicker by group ID. Isn't? If so current article could be modified by adding the groups claim mapping to the script that creates TrustedIdentityTokenIssuer and changes in App Registration manifest. However, if you think it is out of the scope it's ok. :)

**Comment by kaevans** [comment]
The more typical workflow is to assign site permissions by name rather than ID. For instance, adding the group in People picker as "mytesto365group" (as most users would expect) writes the following to the database:

`c:0ǵ.t|azuread|mytesto365group`

Authentication fails because the claim that is posted includes the object ID, not the group name.

Instead, add the group using its object ID in the people picker (since this is the value that is posted in the SAML requestsecuritytokenresponse) as "295095e9-a271-4306-94b4-8e11f41fbfbd". This ends up in the database:

`c:0ǵ.t|azuread|295095e9-a271-4306-94b4-8e11f41fbfbd`

Authentication now works. I don't think typical users would be willing to go look up guids for O365 group IDs, this seems like a very limited scenario. Yes, it enables permission grants by groups, but this scenario is much more elegantly handled by a custom claims provider that provides claims augmentation and can perform group membership queries via Graph API calls. 

Here are the steps to get it working if anyone so wishes. If you feel strongly about adding this to the article, feel free to submit a pull request and we'll review. 

1) Update the app manifest by going to App Registrations / View all applications. Go to the Manifest button and update the value  for groupMembershipClaims to "All":

`"groupMembershipClaims": "All"`

2) Update the STS to include the group claim type mapping.
`$sts = Get-SPTrustedIdentityTokenIssuer AzureAD 
$sts.ClaimTypes.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/groups")
$map4 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups" -IncomingClaimTypeDisplayName "Groups" -SameAsIncoming
Add-SPClaimTypeMapping -Identity $map4 -TrustedIdentityTokenIssuer $sts`

3) Add the user to an O365 group in AAD. Go to the Properties tab of the group and copy the object ID. Also make sure to grant the O365 group permission to the app registration.

4) Log into SharePoint as a user with permission to manage site permissions. Add the group's object ID and select the "Groups" claim in the people picker.

5) You can now log into the SharePoint site as a user that is a member of the O365 group.
