### ISSUE TITLE
Sharepoint 2013 Setup

### ISSUE THREAD

**Issue by brianmaurer** [MicrosoftDocs/OfficeDocs-Enterprise#11]
I'm trying this with SharePoint 2013 and running into a few issues on the SharePoint side.
If I leave Windows Authentication enabled, as shown above, I get a Windows Authentication dialog box. After authenticating I get an error.
If I turn off Windows Authentication, I get a page not found error.

Do I need to do something differently to get it to work on SharePoint 2013

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication | Microsoft Docs](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
SharePoint 2013 should work the same as 2016. Create a new web application. Extend the web application to a new zone (I chose internet), specifying the SSL settings and configure the certificate. Verify that it works before moving on to configuring the trusted identity provider. Next, make sure that you pick the zone you just extended when configuring auth (internet in my case).

**Comment by stevep4** [comment]
Hi Brian... if it was a 404 error, i got that too, if you look in IIS for the site you're configuring you'll probably find there's no virtual directory for /_trust/. I had to delete the site and re-extend, after that the virtual dir was created ok and it started to work.

Also, step 4 point 4, Custom sign in page, I found it needed to be "/_trust/default.aspx" (rather than just "/_trust/") or I got an error. (kaevans, maybe needs updating in the documentation?).

**Comment by kaevans** [comment]
The steps are written for SharePoint 2016. As noted in the article, it should work for SharePoint 2013 (as you demonstrated) but that product is nearing end of life and customers are urged to upgrade to maintain support.

**Comment by brianmaurer** [comment]
Got it working. My site started as an HTTP site. We added HTTPS support by changing AAM and modifying IIS instead of extending the web app. That's why the /_trust/ folder was missing.

**Comment by ryankirchner** [comment]
Brian - We are attempting to cut over an existing Azure enterprise application using SharePoint 2013 (using ACS) to a new enterprise application using this documentation. I am in the process of creating the new enterprise application in Step 3. Our existing Sharepoint site is public facing at a URL of https://www.<sitename>.com.  Do I need to delete this enterprise application before I create the new one? The new one needs to have the same URL, so deleting the old one would make sense. Also, since the ACS tools are no longer available I am fearful that if this new method you describe in the documentation does not work for whatever reason I will not be able to restore our old site.  Thoughts?

**Comment by ryankirchner** [comment]
https://www.ourdomainname.com

**Comment by brianmaurer** [comment]
I'm not an Azure expert but ... 
I wouldn't delete the existing application.
Have you tried creating a new azure app using the same URL?

**Comment by ryankirchner** [comment]
No, I haven't tried that. Our existing SharePoint site is being used as our extranet so I'm cautious about any downtime.

**Comment by denisebmsft** [comment]
Thanks for the feedback, ryankirchner. We are looking into this and will follow up soon.

**Comment by kaevans** [comment]
Re-opened issue is not the same as original issue. Original issue was how to configure on SP2013, re-opened issue is how to migrate. Migration was answered separately: [Issue 20](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/20)
