### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by lexxus93600** [MicrosoftDocs/OfficeDocs-Enterprise#113]
When trying to follow your guideline, portal Azure notifies me that I need a Premium Azure Active Directory in order to create a "Non-gallery application". So I'm wondering if I need an Azure Active Directory Premium P1 (or P2) for each user in my organization to be able to authenticate them on SharePoint ? It's a big cost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/Office365/Enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Thanks for the feedback, @lexxus93600. I'm looking into this and will post back when I get an answer.

**Comment by denisebmsft** [comment]
@lexxus93600, if you are able to add a gallery application (and apparently you get 10 free), then you don't need the premium version of Azure Active Directory.

**Comment by lexxus93600** [comment]
Without a premium azure ad, I am not able to add a « non gallery application ».
But my question is more about that do I need to have a license per user ? Because with only a single licence I can add a non gallery application and I am be able to authenticate all my azure active directory users into SharePoint, without assigning any azure ad premium license to any user. Only the fact to have a azure ad premium allows me to create that application..

**Comment by denisebmsft** [comment]
@lexxus93600 that is a good question. We'll get the answer.

**Comment by AndreaBarr** [comment]
@lexxus93600 Thank you for this feedback

Since you should be able to add non gallery applications but are not able to I want to get you to support so they can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
