### ISSUE TITLE
Why use a web application policy to grant access in Step 5?

### ISSUE THREAD

**Issue by ferringer** [MicrosoftDocs/OfficeDocs-Enterprise#116]
Is there a required reason why this is a recommended way to grant AAD users access to the web application? It feels fairly heavy handed to grant them access (especially full access) via the web app policy rather than individually within the site collections they need to access. I kind of thought these policies were mostly for service accounts and such, am I misunderstanding a requirement for implementing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication#feedback)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
@ferringer - hey John, this is really for testing purposes. This article really only serves to educate how to perform and confirm an initial configuration, it does not intend to educate users to the nuances of SharePoint authorization and permission models.

We restricted this article to give specific instructions to get a user started, not to provide comprehensive product documentation on how authorization works in various contexts. 

There is a lot of variability in the ways that zones, web applications, and site collections can be provisioned. This article does not propose to clarify all the various combination. Rather, this article shows how to configure a single user to auth against AAD. This topic could cover a book, and nearly has (see Steve Peschka's blog as an example). The web application policy is used in this context because it goes against the STS and is much less complicated than trying to instruct how to restrict access to a list.

There are a ton of additional considerations such as using groups, creating custom claims providers, splitting auth per zone, using different host headers per site collection per zone, configuring site collection permissions, application permissions, list permissions, breaking inheritance, search experience for claims users, user profile property mapping, user profile import for claims users, app service for claims users, workflows for claims users... we could write about this extensively and still not cover all customer use cases. We cannot fit them all here, if you see that we missed any we welcome that feedback. 

If there are additional improvements to this article that you feel are needed, please consider forking this repo and creating a pull request for your changes.
