### ISSUE TITLE
Single sign on and sign out

### ISSUE THREAD

**Issue by unnieayilliath** [MicrosoftDocs/OfficeDocs-Enterprise#127]
I can understand that single sign on will work in this scenario. But will these steps provide single sign out between the on prem SP sites and other apps (eg: SPO sites) integrated with same Azure AD also? Since SharePoint works with fed-auth cookie will it not just ignore that the user has been logged out from Azure from some different application ? It will be nice to have some information about that in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
To enable signout, configure the SharePoint STS with a ProviderSignOutUri property. This will sign the user out of SharePoint then redirect them to the provider's signout URL, which signs them out of AzureAD and, if present, your federation service (such as ADFS).

```
$sts = Get-SPTrustedIdentityTokenIssuer AzureAD
$sts.ProviderSignOutUri = "https://login.microsoftonline.com/common/wsfederation"
$sts.Update()
```

**Comment by kaevans** [comment]
@unnieayilliath that's correct, the default behavior is that the user is authenticated and a persistent FedAuth cookie is stored for the user with a default lifetime of 10 hours. Note that a change in SP2016 may mean that the token is automatically refreshed (see the second article below). Logging out of AAD does not affect the validity or lifetime of the FedAuth cookie issued by SharePoint. 

A change you may want to investigate is to use session cookies instead of persistent cookies so that the user's FedAuth cookie is deleted when the browser is closed:

```
$sts = Get-SPSecurityTokenServiceConfig
$sts.UseSessionCookies =$true
$sts.Update()
```
To test this change, log into SharePoint, then open a new tab and visit myapps.microsoft.com. You will not need to log in again to access this site. Now go to the top right, click your name, and choose "Sign out". You are now logged out of AzureAD, and instructed in the resulting window to close all browser windows. If you close only that tab and then go back to the tab with SharePoint and note that you are able to continue accessing the SharePoint site as long as the token is valid. Now close all browser windows. Open the browser again, you are now required to sign in again.

Note that this may or may not be a desirable change based on your requirements. Some customers want to limit the number of times users are prompted to log in and prefer persistent cookies. 

Besides this configuration setting, there are more configuration settings for SharePoint's STS to control the token lifetime and cookie lifetime based on your requirements. For more information, see:

- [SharePoint 2013 authentication lifetime settings](https://blogs.msdn.microsoft.com/jesusfer/2015/08/27/sharepoint-2013-authentication-lifetime-settings/)
- [SharePoint 2016: FBA authentication changes](https://blogs.technet.microsoft.com/spjr/2018/07/11/sharepoint-2016-fba-authentication-changes/)

**Comment by sabeesharif** [comment]
I have SharePoint 2010 how i can set SignOutUri because ProviderSignOutUri is not supported by SharePoint 2010?
$sts = Get-SPTrustedIdentityTokenIssuer AzureAD
$sts.ProviderSignOutUri = "https://login.microsoftonline.com/common/wsfederation"
$sts.Update()

any solution instead of custom control code?
