### ISSUE TITLE
can I install both Azure Active Directory module V1 and Azure Active Directory Module V2 at the same time?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/OfficeDocs-Enterprise#159]
can I install and use both the Azure Active Directory PowerShell for Graph module and the Microsoft Azure Active Directory Module for Windows PowerShell on the same computer at the same time? 

I will use this on the Azure AD Connect server, which synchronises &gt;50K user accounts in a highly dynamic environment, so I *CANNOT* afford to take any risks!  Can you confirm that they will happily coexist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb1fe83-c1b3-3176-4d61-fe4f3ce1d598
* Version Independent ID: c89f295b-4f00-c2c0-c75f-75fa50ecda65
* Content: [Connect to Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell)
* Content Source: [Enterprise/powershell/connect-to-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/connect-to-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by AndreaBarr** [comment]
@anwarmahmood1 Thank you for this feedback

I want to make sure you get help ASAP. We aren't equiped for support here on the forums. I want to get you over to the Support team so that we can get this question answered for you. I undersatnd the importance on speed with this since you are mid-migration and have users waiting on you. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by anwarmahmood1** [comment]
I opened an incident with Microsoft; a Microsoft support engineer covering cloud identity confirmed "there won’t be any problem in installing the 2 PowerShell modules in the same computer. This is usually how customers use PowerShell because depending to the cmdlet you are using you need to use the Msol or the AzureAD."

Hence, I would recommend at the end of "What do you need to know before you begin?", add

there are two version of Azure Active Directory module for Powershell;
 - Microsoft Azure Active Directory Module for Windows PowerShell (cmdlets include 'msol'; V1)
 - Azure Active Directory PowerShell for Graph (cmdlets include 'AzureAD'; V2)

As of October 2018, Azure Active Directory PowerShell for Graph (cmdlets include 'AzureAD'; V2) does not completely replace Microsoft Azure Active Directory Module for Windows PowerShell (cmdlets include 'msol'; V1), so you may need to install both versions. You can safely install both versions on the same computer.

**Comment by AndreaBarr** [comment]
@anwarmahmood1 Thank you for giving us feedback on what you learned from support

I will get this over to the Enterprise team so that we can make sure to get this information added to the article. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by JoeDavies-MSFT** [comment]
@anwarmahmood1 The article has been updated to include your information suggestions. Thanks for the assistance and the push.
