### ISSUE TITLE
does the solution work with sharepoint extranet web application using Azure AD

### ISSUE THREAD

**Issue by leov6** [MicrosoftDocs/OfficeDocs-Enterprise#161]
i followed the exact step here against our sharepoint 2013 web application (extranet zone) published using ADFS 3.0 and WAP.  but, after successful login at Azure AD, i get the web.config error at the https://extranet_SP_URL/_trust page.  any idea why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by AndreaBarr** [comment]
@leov6 Thank you for this feedback

I agree with Guptas that this should work. If double checking your reply URL doesn't get this to work then the best thing I can have you do is contact Support so that we can see exactly what is going on. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
