### ISSUE TITLE
Developers 

### ISSUE THREAD

**Issue by jcgithubdeveloper** [MicrosoftDocs/OfficeDocs-Enterprise#239]
Can you please help me fixing all issues

**Comment by AndreaBarr** [comment]
@jcgithubdeveloper Thank you for this inquiry

If you are having an issue with an article we can for sure help with that. If your having an issue with a product then the best thing we can do is get you over to Support since they have more resources than we do here to help dig in and find a resolution.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
