### ISSUE TITLE
Session timeout for Skype for Business client

### ISSUE THREAD

**Issue by TonyRogersAU** [MicrosoftDocs/OfficeDocs-Enterprise#245]
What is the session timeout for Skype for Business Client when running in hybrid mode?

We have Lync server on premises and Exchange Online in O365.  
How often will the SfB client request a new refresh token for EXO with Modern Auth and MFA activated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1570de51-50b1-d4cc-c1c7-832b3242ccb3
* Version Independent ID: f5250f91-0a48-20cf-8e2c-e2dc347edd88
* Content: [Session timeouts for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/session-timeouts)
* Content Source: [Enterprise/session-timeouts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/session-timeouts.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by robmazz** [comment]
@TonyRogersAU - thanks for the feedback, I'll get this over to the Enterprise content team for review.

**Comment by MSFTTracyP** [comment]
This is a good question, and one I think we can break down into segments, like the traffic across a hybrid environment / network. I don't know what your environment looks like, but your answer can change based on a) timeout tweaks an admin may have made, b) what devices you use in your hybrid, and c) how often user passwords change inside your organization.

I would need to know whether your hybrid used ADFS between the on-premises client and Office 365, for one thing. The ADFS server session is going to expire in roughly 8 hours and that will mean users will be prompted to authenticate.

Likewise, Multifactor-Auth (MFA) has a verification timeout that can sometimes be tweaked in the client registry, for example. When the MFA is in the Cloud, you can't change the default verification timeout of 180 seconds, and this will impact users who can't validate in time.

Ultimately, the 'Azure Active Directory (used by Office 2013 and Windows clients with modern authentication enabled)' section of the source article actually outlines the token timeouts common, or default in OAuth or S2S auth. This is an underlying protocol of Modern Authentication. Understand that when the table says that any refresh tokens are valid for 90 days, that this is impacted by password changes, and policies. Incorrect logins can result in prompts.

What I *don't know* right now is whether there's a timeout associated with the Skype for Business client itself (or the client registry). I'm checking into that for you now, but replies will be a little dodgy -- I'm sorry to say -- due to the holiday.

Please keep in touch. Sorry for any delays.
