### ISSUE TITLE
URL Default Internal vs Extended External Site can they be the same?

### ISSUE THREAD

**Issue by moojjoo** [MicrosoftDocs/OfficeDocs-Enterprise#274]
Example:

https://www.mydomain.com/ = Default internal (Note SSL is being used)

Question: Is it possible to have the extended different zone with the same URL https://www.mydomain.com/ or does it have to be different.  Asking the question, because what if an internal users wants to copy and paste a URL with an external user?  If you cannot use the same url how can you work around this?  Is it possible or explained to the external users they have to add -ext like https://www.mydomain-ext.com/ ????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
So each zone URL is different, and may be handled by a different DNS. The Internal URL sharepoint.litware.com can be managed by internal DNS, while Sharepoint-external.litware.com may be the extranet zone URL. These URLs actually correspond to different IIS web applications, and can have their own CAs, certificates, authentication methods, and distributed cache settings. You should not extend a second web application and create a Zone URL with the same URL as the first Zone. Though I believe the Public URL would resist being added a second time, the underlying instance of IIS and its wiring (http.sys, w3wp.exe, et cetera) could give you highly inconsistent results, because it is using the URL supplied to select the proper web application for your request.

Likewise, your extranet users would be browsing SharePoint-external.litware.com, and their relative URLs would come back with the same Public URL. They wouldn't be expecting sharepoint.litware.com (this is a bit of a bad example, but imagine that the internal URL is something more like http://sp-int and you'll see that there can be a major difference). The relative URLs could be shared, but your audiences are different here so extranet and internet browsers may not see everything your intranet users do. You could explain that the root domain in different for the extranet users, but that might not explain why some internal URLs are not accessible / external users have no access. Breaking the wall between these Zones begs the question of why a user who repeatedly needs access to the intranet zone isn't in that zone, or why sites with shared data aren't permissioned to appear in the extranet zone for some users.

**Comment by moojjoo** [comment]
MSFTTracyP, I am applauding this answer.  Excellent explanation and yes the external personnel do see different views than external.  My belief is that it is a training exercise that needs training to internal (Sponsors/Delegates) aka internal domain users who might send an email to an external counterpart to access the site, need to be sure to add the "-ext" in the url.   I am not sure if this will ever even happen but wanted to be able to get the SOURCE aka MSFT to provide me with a clear explanation when I am asked.

Thank you again MSFTTracyP.   Close the ISSUE thx.
