### ISSUE TITLE
Missing IP address for microsoft.sharepoint.com

### ISSUE THREAD

**Issue by nm999** [MicrosoftDocs/OfficeDocs-Enterprise#337]
*.sharepoint.com is in the "Optimize" category in the Office 365 URLs list so we have it in our web proxy bypass list and we allow those URLs directly out our firewall.  microsoft.sharepoint.com, however, resolves to IP address 13.107.18.14. This IP address is not in any of the IP address ranges. The closest match is 13.107.18.10/31 but it doesn't fall within that subnet though.

**Comment by JoeDavies-MSFT** [comment]
@nm999 microsoft.sharepoint.com is the FQDN is for the central SharePoint portal for the Microsoft Corporation's Office 365 tenant. It is not a public web site. The IP address you cite above is for that purpose, and therefore does not belong in the list of public IP addresses to allow or block. Thanks for you question.

**Comment by nm999** [comment]
> @nm999 microsoft.sharepoint.com is the FQDN is for the central SharePoint portal for the Microsoft Corporation's Office 365 tenant. It is not a public web site. The IP address you cite above is for that purpose, and therefore does not belong in the list of public IP addresses to allow or block. Thanks for you question.

@JoeDavies-MSFT  Hi, thanks for the reply. That means any time a user is invited to another organisation's tenant e.g. Microsoft corporation's sharepoint site as in this case, then our proxy bypass list will stop them accessing that portal as the list of IP addresses configured on the firewall won't match for that tenant FQDN and we will need to make manual intervention every time. The user won't have an idea why they cannot account the other organisation's tenant.

As a result the Optimize list should not include the wildcard *.sharepoint.com but only the the FQDNs that have a corresponding IP address for in the IP address range list. This must be an issue for other organisations out there also as there is quite a bit of inviting users to each other organisation's tenants to access resources there.

**Comment by cimares** [comment]
@JoeDavies-MSFT - Might need to consider a change that addresses this issue. I'm working with a client that restricts access by IP and URL filtering, bypassing everything for SharePoint.Com as we'd expect, however staff being invited to work directly with Microsoft in their teams implementation are being blocked by our proxies, because it can't categorise the site.

As @nm999 points out, the microsoft.sharepoint.com resolves to an IP address outside of the public ranges which we can bypass, but I can't guarantee that this is the only IP that we may need to talk to when working with Microsoft directly. A small note in the document that details what addresses to bypass if working directly with MS would be useful (And hardly sensitive.)
