### ISSUE TITLE
Statement regarding navigation options

### ISSUE THREAD

**Issue by taisino** [MicrosoftDocs/OfficeDocs-Enterprise#451]
We have seen many “blogs” and “docs” stating structural navigation is not recommended on SPO, but customer is asking for more strict public statement warning customer about the usage.
As one of the example;
 “Structural navigation, is NOT a recommended navigation option in SharePoint Online.”

Japanese customer feels that “Not recommended” is weak expression and should be replaced with firm words like “not supported”. Otherwise they would not foresee this kind of sluggish performance and even operation outage by this option.
I believe this is the cultural issue and specific in Japan, but I would be grateful if you could do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe686368-f607-9a7d-710b-d51c3f8f6c9a
* Version Independent ID: 01b5902a-6e23-62d9-f0a3-7c1e86194ef1
* Content: [Navigation options for SharePoint Online](https://docs.microsoft.com/en-us/office365/enterprise/navigation-options-for-sharepoint-online?redirectSourcePath=%252fja-jp%252farticle%252fadb92b80-b342-4ecb-99a1-da2a2b4782eb)
* Content Source: [Enterprise/navigation-options-for-sharepoint-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/navigation-options-for-sharepoint-online.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@taisino - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@KCCross - Can you please share your insights on this issue? 

Thank you.

**Comment by KCCross** [comment]
I understand the concern. The statement was accurate as published. SPO administrators could expect performance degradation with this kind of navigation. However, in some cases, this might have been the appropriate navigation type. I will ask the current owner of the content to check back with the product team to see if there are any updates since SPO has undergone significant performance improvements since I initially wrote this piece. I will also update the owner field with the new owner's ID. I apologize that this housekeeping was not already complete! Thank you for your careful reading of the content.

**Comment by mypil** [comment]
@taisino - From our understanding, the issue has been answered by KCCross. If you feel it hasn't been resolved, please re-open this issue.

Thank you for engaging with the community here for the docs.

**Comment by mypil** [comment]
@officedocsbot close
