### ISSUE TITLE
I am at the end of Phase 2: Configure DC1 and hitting an error

### ISSUE THREAD

**Issue by seenaomi** [MicrosoftDocs/OfficeDocs-Enterprise#46]
I am at the end of Phase 2: Configure DC1

I ran this: 

PS C:\Users\ngsee> $vm=Add-AzureRmVMDataDisk -VM $vm -Name "DC1-DataDisk1" -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 1
New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm

WARNING: New-AzureRmVM: A property of the output of this cmdlet will change in an upcoming breaking change release. The StorageAccountType proper
ty for a DataDisk will return Standard_LRS and Premium_LRS
WARNING: Since the VM is created using premium storage, new standard storage account, freeteamrddc1050115520, is created for boot diagnostics.
New-AzureRMVM : Error converting value "StandardLRS" to type 
'System.Nullable`1[Microsoft.Azure.XStoreClientHelper.StorageAccountServiceClient.StorageAccountType]'. Path 
'properties.storageProfile.osDisk.managedDisk.storageAccountType', line 19, position 45.
ErrorCode: BadRequest
ErrorMessage: Error converting value "StandardLRS" to type 
'System.Nullable`1[Microsoft.Azure.XStoreClientHelper.StorageAccountServiceClient.StorageAccountType]'. Path 
'properties.storageProfile.osDisk.managedDisk.storageAccountType', line 19, position 45.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 01587bca-124d-4f91-a8a2-ff545ef4c13d
At line:2 char:1
+ New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

My team is TeamRDX - the activity
 log shows no other failures - I was referred here by chat to post my issue.

This tutorial is pretty basic and
 mostly copy/paste outside of setting the ResourceGroup and Location - not much room for user error essentially.

Can you help determine the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136007e4-4ddd-a1d8-a3ac-251da6bd5311
* Version Independent ID: 5c1ec643-ac23-cf7c-c787-3ffb1b4f9674
* Content: [Base Configuration dev/test environment](https://docs.microsoft.com/en-us/office365/enterprise/base-configuration-dev-test-environment)
* Content Source: [Enterprise/base-configuration-dev-test-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/base-configuration-dev-test-environment.md)
* Service: **o365-solutions**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by seenaomi** [comment]
The documentation needs to be updated:
Current:
$vm=Set-AzureRmVMOSDisk -VM $vm -Name "DC1-OS" -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType "StandardLRS"
$diskConfig=New-AzureRmDiskConfig -AccountType "StandardLRS" -Location $locName -CreateOption Empty -DiskSizeGB 20

Needs to be updated too: 
$vm=Set-AzureRmVMOSDisk -VM $vm -Name "DC1-OS" -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType "Standard_LRS"
$diskConfig=New-AzureRmDiskConfig -AccountType "Standard_LRS" -Location $locName -CreateOption Empty -DiskSizeGB 20

**Comment by denisebmsft** [comment]
Thanks seenaomi!

**Comment by Dudenstein** [comment]
Hi, I am also getting an error when I try and create DC1 VM:

Here is what I have entered:
$rgName="o365testlab"
$locName=(Get-AzureRmResourceGroup -Name $rgName).Location
$vnet=Get-AzureRMVirtualNetwork -Name TestLab -ResourceGroupName $rgName
$pip=New-AzureRMPublicIpAddress -Name DC1-PIP -ResourceGroupName $rgName -Location $locName -AllocationMethod Dynamic
$nic=New-AzureRMNetworkInterface -Name DC1-NIC -ResourceGroupName $rgName -Location $locName -SubnetId $vnet.Subnets[0].Id -PublicIpAddressId $pip.Id -PrivateIpAddress 10.0.0.4
$vm=New-AzureRMVMConfig -VMName DC1 -VMSize Standard_A1
$cred=Get-Credential -Message "Type the name and password of the local administrator account for DC1."
$vm=Set-AzureRMVMOperatingSystem -VM $vm -Windows -ComputerName DC1 -Credential $cred -ProvisionVMAgent -EnableAutoUpdate
$vm=Set-AzureRMVMSourceImage -VM $vm -PublisherName MicrosoftWindowsServer -Offer WindowsServer -Skus 2016-Datacenter -Version "latest"
$vm=Add-AzureRMVMNetworkInterface -VM $vm -Id $nic.Id
$vm=Set-AzureRmVMOSDisk -VM $vm -Name "DC1-OS" -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType StandardLRS
$diskConfig=New-AzureRmDiskConfig -AccountType StandardLRS -Location $locName -CreateOption Empty -DiskSizeGB 20
$dataDisk1=New-AzureRmDisk -DiskName "DC1-DataDisk1" -Disk $diskConfig -ResourceGroupName $rgName
$vm=Add-AzureRmVMDataDisk -VM $vm -Name "DC1-DataDisk1" -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 1
New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm

here is the error I get (even after removing the quotation marks from "StandardLRS"

WARNING: Since the VM is created using premium storage or managed disk, existing standard storage account, visuao365tedc1050411480, is used for boot diagnostics.
New-AzureRMVM : Error converting value "StandardLRS" to type 'System.Nullable`1[Microsoft.Azure.XStoreClientHelper.StorageAccountServiceClient.StorageAccountType]'. Path 
'properties.storageProfile.osDisk.managedDisk.storageAccountType', line 19, position 45.
ErrorCode: BadRequest
ErrorMessage: Error converting value "StandardLRS" to type 'System.Nullable`1[Microsoft.Azure.XStoreClientHelper.StorageAccountServiceClient.StorageAccountType]'. Path 
'properties.storageProfile.osDisk.managedDisk.storageAccountType', line 19, position 45.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : afa79074-53fe-44a8-acd3-13500a0f3e01
At line:15 char:1
+ New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

**Comment by DonnieAsh** [comment]
I am at the end of DC1 and keep getting this error when told to add the User1 in the Active Directory

New-ADUser : The term 'New-ADUser' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ New-ADUser -SamAccountName User1 -AccountPassword (read-host "Set use ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-ADUser:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by JoeDavies-MSFT** [comment]
seenaomi and Dudenstein, I have updated the PowerShell to remove the quotes around the instances of StandardLRS. Thanks for letting me know. Joe

**Comment by JoeDavies-MSFT** [comment]
DonnieAsh, The PowerShell command "Install-WindowsFeature AD-Domain-Services -IncludeManagementTools" when configuring DC1 should have installed the Windows Server Active Directory module that contains the New-ADUser cmdlet. See https://4sysops.com/wiki/how-to-install-the-powershell-active-directory-module/ for instructions to manually add the AD PowerShell module. Joe

**Comment by ashunt677** [comment]
On Phase 3: Configure App 1, I am stuck on the part involving joining App1 to the corp.contoso.com domain: "To check name resolution and network communication between APP1 and DC1, run the ping dc1.corp.contoso.com command and verify that there are four replies.

Next, join the APP1 virtual machine to the CORP domain with these commands at the Windows PowerShell prompt.

Add-Computer -DomainName corp.contoso.com
Restart-Computer
This fails in powershell, also fails in GUI system properties with:
The following error occurred when DNS was queried for the service location (SRV) resource record used to locate an Active Directory Domain Controller (AD DC) for domain "corp.contoso.com":

The error was: "DNS name does not exist."
(error code 0x0000232B RCODE_NAME_ERROR)

The query was for the SRV record for _ldap._tcp.dc._msdcs.corp.contoso.com

Common causes of this error include the following:

- The DNS SRV records required to locate a AD DC for the domain are not registered in DNS. These records are registered with a DNS server automatically when a AD DC is added to a domain. They are updated by the AD DC at set intervals. This computer is configured to use DNS servers with the following IP addresses:

168.63.129.16

- One or more of the following zones do not include delegation to its child zone:

corp.contoso.com
contoso.com
com
. (the root zone)

I can ping dc1 by name or number with the below results:
C:\Windows\system32>ping dc1

Pinging dc1.fqjm0ggwz0ueha2myufwf4ajkh.gx.internal.cloudapp.net [10.0.0.5] with 32 bytes of data:
Reply from 10.0.0.5: bytes=32 time=2ms TTL=128

DNS is installed on DC1, in DNS properties I see DNS IP 168.63.129.16 green check marked, however, FQDN is <unable to resolve>
I have successfully finished all other steps up to this point, including the NetFirewallRule

**Comment by ashunt677** [comment]
Dudenstein and Medavamshi, did you try Standard_LRS instead of StandardLRS? I ran into this roadblock a few weeks ago so I don't recall how I got past it, but I didn't put an entry in my notes for this part of the lab, so either it was an easy fix or I got lazy. Think you're on the right track though.

**Comment by ashunt677** [comment]
On my original posting above - On Phase 3: Configure App 1 - I created a new issue/thread for it, as it didn't pertain to the topic this thread had begun.

**Comment by JoeDavies-MSFT** [comment]
@medavamshi , I just tested this using the instructions and syntax (Set-AzureRmVMOSDisk -VM $vmConfig -Name $osDiskName -DiskSizeInGB $osDiskSize -CreateOption FromImage -StorageAccountType StandardLRS) and it worked fine. What version of Azure PowerShell are you using? Thanks

**Comment by JoeDavies-MSFT** [comment]
@ashunt677 I just tested this using the instructions. If you can't resolve dc1.corp.contoso.com, then the DC1 VM must not have been promoted to a domain controller. When DC1 is promoted, it also becomes the DNS server for all the virtual machines in the Corpnet subnet. Take a look at DC1. Joe

**Comment by ashunt677** [comment]
@JoeDavies-MSFT DC1 was always promoted but i did a demote-promote anyway. After that didn't work I changed APP1 DNS to point to DC1 (10.0.0.5) that was not a good idea, I lost my ability to RDP to it. Instead of recreating the VM, I got in some practice with serial console (preview) and set DNS back to Dynamic. 
The FIX: in Azure portal, changed the virtual network dns to primary:10.0.0.5 secondary: 168.63.129.16. After that app1 and client1 as well joined the domain no problem.

**Comment by FrankvL** [comment]
When I run the script to create DC1 I got the following error
PS N:\> # Create the DC1 VM
>> $rgName="RG-Test"
>> $locName=(Get-AzureRmResourceGroup -Name $rgName).Location
>> $vnet=Get-AzureRMVirtualNetwork -Name TestLab -ResourceGroupName $rgName
>> $pip=New-AzureRMPublicIpAddress -Name DC1-PIP -ResourceGroupName $rgName -Location $locName -AllocationMethod Dynamic
>> $nic=New-AzureRMNetworkInterface -Name DC1-NIC -ResourceGroupName $rgName -Location $locName -SubnetId $vnet.Subnets[0].Id -PublicIpAddressId $pip.Id -PrivateIpAddress 10.0.0.4
>> $vm=New-AzureRMVMConfig -VMName DC1 -VMSize Standard_A1
>> $cred=Get-Credential -Message "Type the name and password of the local administrator account for DC1."
>> $vm=Set-AzureRMVMOperatingSystem -VM $vm -Windows -ComputerName DC1 -Credential $cred -ProvisionVMAgent -EnableAutoUpdate
>> $vm=Set-AzureRMVMSourceImage -VM $vm -PublisherName MicrosoftWindowsServer -Offer WindowsServer -Skus 2016-Datacenter -Version "latest"
>> $vm=Add-AzureRMVMNetworkInterface -VM $vm -Id $nic.Id
>> $vm=Set-AzureRmVMOSDisk -VM $vm -Name "DC1-OS" -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType Standard_LRS
>> $diskConfig=New-AzureRmDiskConfig -AccountType Standard_LRS -Location $locName -CreateOption Empty -DiskSizeGB 20
>> $dataDisk1=New-AzureRmDisk -DiskName "DC1-DataDisk1" -Disk $diskConfig -ResourceGroupName $rgName
>> $vm=Add-AzureRmVMDataDisk -VM $vm -Name "DC1-DataDisk1" -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 1
>> New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm
>>
WARNING: The output object type of this cmdlet will be modified in a future release.
WARNING: The output object type of this cmdlet will be modified in a future release.
WARNING: Since the VM is created using premium storage, new standard storage account, gratirgtesdc1081610230, is created for boot
diagnostics.
New-AzureRMVM : Object reference not set to an instance of an object.
At line:16 char:1
+ New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

I user AzureRM 6.3.0
PS N:\> get-module -name AzureRM -ListAvailable
Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.3.0      AzureRM

**Comment by ashunt677** [comment]
Is it the hyphen in "RG-Test" ? try "RG'-Test" or just use _

**Comment by emashiring** [comment]
Hello, I have been having a challenge creating an Azure VM using the scripts on this document (today's date 20th August 2018). I get the error when I run the last PowerShell command under Phase 2: Configure DC1.
[ New-AzureRMVM -VM $vm -ResourceGroupName $rgName -Location $locName ]
it was creating a storage account prior to returning the error which shown below. So I decided to create a storage account to see what happens.  Please see below.
_______________________
New-AzureRmStorageAccount -ResourceGroupName $rgName -Name "storagequickstart22" -Location $locName -SkuName Standard_LRS -Kind StorageV2

StorageAccountName  ResourceGroupName    Location SkuName     Kind      AccessTier CreationTime        ProvisioningStat
                                                                                                       e
------------------  -----------------    -------- -------     ----      ---------- ------------        ----------------
storagequickstart22 myTest2ResourceGroup uksouth  StandardLRS StorageV2 Hot        20/08/2018 11:00:24 Succeeded


PS C:\Windows\system32> New-AzureRMVM -VM $vm -ResourceGroupName $rgName -Location $locName
WARNING: Since the VM is created using premium storage or managed disk, existing standard storage account,
storagequickstart22, is used for boot diagnostics.
New-AzureRMVM : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzureRMVM -VM $vm -ResourceGroupName $rgName -Location $locName
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

_____________________________________
I am running 
Get-Module -ListAvailable -Name Azurerm -Refresh


Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.7.0      AzureRM

Looking for any help if anyone can suggest what else to try?

**Comment by takayakawano** [comment]
Hi Team, I had a same error. this command is based on [Phase 2: Configure DC1](https://docs.microsoft.com/en-us/office365/enterprise/base-configuration-dev-test-environment#phase-2-configure-dc1). Could you please provide solution if this error resolved.

**Entered Command:** 
PS C:\WINDOWS\system32> $locName=(Get-AzureRmResourceGroup -Name $rgName).Location
$vnet=Get-AzureRMVirtualNetwork -Name TestLab -ResourceGroupName $rgName
$pip=New-AzureRMPublicIpAddress -Name DC1-PIP -ResourceGroupName $rgName -Location $locName -AllocationMethod Dynamic
$nic=New-AzureRMNetworkInterface -Name DC1-NIC -ResourceGroupName $rgName -Location $locName -SubnetId $vnet.Subnets[0].Id -PublicIpAddressId $pip.Id -PrivateIpAddress 10.0.0.4
$vm=New-AzureRMVMConfig -VMName DC1 -VMSize Standard_A1
$cred=Get-Credential -Message "Type the name and password of the local administrator account for DC1."
$vm=Set-AzureRMVMOperatingSystem -VM $vm -Windows -ComputerName DC1 -Credential $cred -ProvisionVMAgent -EnableAutoUpdate
$vm=Set-AzureRMVMSourceImage -VM $vm -PublisherName MicrosoftWindowsServer -Offer WindowsServer -Skus 2016-Datacenter -Version "latest"
$vm=Add-AzureRMVMNetworkInterface -VM $vm -Id $nic.Id
$vm=Set-AzureRmVMOSDisk -VM $vm -Name "DC1-OS" -DiskSizeInGB 128 -CreateOption FromImage -StorageAccountType Standard_LRS
$diskConfig=New-AzureRmDiskConfig -AccountType Standard_LRS -Location $locName -CreateOption Empty -DiskSizeGB 20
$dataDisk1=New-AzureRmDisk -DiskName "DC1-DataDisk1" -Disk $diskConfig -ResourceGroupName $rgName
$vm=Add-AzureRmVMDataDisk -VM $vm -Name "DC1-DataDisk1" -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 1
New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm

**Error:** 
WARNING: The output object type of this cmdlet will be modified in a future release.
WARNING: The output object type of this cmdlet will be modified in a future release.
WARNING: Since the VM is created using premium storage, new standard storage account, visuatesto3dc1082221030, is created for boot diagnostics.
New-AzureRMVM : Object reference not set to an instance of an object.
At line:14 char:1
+ New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

**Comment by JoeDavies-MSFT** [comment]
@takashi-moriyama I just tested this again with Azure module version 6.4.0 and it worked. I have added a note throughout that you need to ensure that the VM size must be supported in the region (location) in which you are deploying, as others have indicated. I have also added a section that describes a new ARM template to deploy this configuration.

**Comment by JoeDavies-MSFT** [comment]
@takayakawano I just tested this again with Azure module version 6.4.0 and it worked. I have added a note throughout that you need to ensure that the VM size must be supported in the region (location) in which you are deploying, as others have indicated. I have also added a section that describes a new ARM template to deploy this configuration.
