### ISSUE TITLE
Hybrid configuration 

### ISSUE THREAD

**Issue by CountlessNumber** [MicrosoftDocs/OfficeDocs-Enterprise#490]
Will a 2010 hybrid configuration to 365 actually stop functioning on January 14?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26d825a5-1ac4-9c43-480e-38d88424272a
* Version Independent ID: 5af73b69-8c22-31f4-74a0-0273a240a240
* Content: [Exchange 2010 end of support roadmap](https://docs.microsoft.com/en-us/office365/enterprise/exchange-2010-end-of-support#feedback)
* Content Source: [Enterprise/exchange-2010-end-of-support.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/exchange-2010-end-of-support.md)
* Service: **o365-administration**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@CountlessNumber  - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@dstrome - Can you please share your insights on this issue?

Thank you.

**Comment by mypil** [comment]
@CountlessNumber - It may still work but based on the document, it is indicated that 

"_When Exchange 2010 reaches its end of support on January 14, 2020, Microsoft will no longer provide:

- Technical support for problems that may occur;
- Bug fixes for issues that are discovered and that may impact the stability and usability of the server;
- Security fixes for vulnerabilities that are discovered and that may make the server vulnerable to security breaches;
- Time zone updates.

**Your installation of Exchange 2010 will continue to run after this date. However, because of the changes listed above, we strongly recommend that you migrate from Exchange 2010 as soon as possible.**_"

We hope this helps to address your issue. Thank you.

**Comment by mypil** [comment]
@officedocsbot close
