### ISSUE TITLE
SearchWindowsPrincipal cannot read AzureCP users

### ISSUE THREAD

**Issue by LionfishSecurity** [MicrosoftDocs/OfficeDocs-Enterprise#61]
A large SharePoint tools vendor is telling me that the AzureCP claims provider breaks their software because the identities cannot be read using the Microsoft.SharePoint.Utilities.SPUtility.SearchWindowsPrincipals method.  Does this make sense?  Does the method name indicate that only Windows Principals will be searched?   If there any way that SharePoint can be configured to use AzureCP that permits the SearchWindowsPrincipals method to make use of Azure Active Directory identities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
I am unaware of any documentation that lists the features that do or don't work with SharePoint 2013 or SharePoint 2016 and SAML claims authentication. You should work with the tools vendor in question to ask if their tools don't work with SAML claims or if the issue is specific to the AzureCP claims provider. 

For general questions on SharePoint administration, see https://sharepoint.stackexchange.com/. 

For questions specific to the AzureCP solution, see https://github.com/Yvand/AzureCP.

**Comment by LionfishSecurity** [comment]
Thanks!

**Comment by kaevans** [comment]
@denisebmsft please close.
