### ISSUE TITLE
Alert Policies after changing global admin users

### ISSUE THREAD

**Issue by acraftydev** [MicrosoftDocs/OfficeDocs-Enterprise#618]
I'm following the guidance to create separate logins for my global admin roles. To give those accounts the minimum footprint they have no mailbox associated with them. When I look in the 'Security & Compliance' portal there are a number of default Alert Polices that are configured to goto a dynamic group 'TenantAdmins'. So I am now no longer getting any of these alerts as the new admin accounts have no email. How can I ensure that i get those alerts, I don't want to go through all the alerts and set new recipients as i may miss new ones in the future or there maybe other parts of O365 alerting to the TenantAdmins group. What's the best practice for maintaining alerts after creating separate global admin roles?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96784dc6-991a-fb80-cd0c-ae8217c32f45
* Version Independent ID: 0532ace1-bf55-916f-708d-5444c49d77b1
* Content: [Protect your Office 365 global administrator accounts](https://docs.microsoft.com/en-us/office365/enterprise/protect-your-global-administrator-accounts?source=docs#feedback)
* Content Source: [Enterprise/protect-your-global-administrator-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/protect-your-global-administrator-accounts.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by markjjo** [comment]
@acraftydev You have some options, but you've already identified some of the shortcomings. But alert notifications are email messages and email messages are sent to a mailbox. Here are 4 ideas:

1. You and other admins can monitor the alerts that are generated by alert policies on the Alerts page in the Security and Compliance Center.  You'd have to make a point of going to this page on a regular basis.

2. (Assumes you have at least one mailbox for the tenant admin). Give global admins FullAccess permissions to the tenant admin account that has a mailbox. Then global admins can open this mailbox in Outlook or OWA to monitor alert notifications.

3. Set up an inbox rule or transport rule on the tenant admin mailbox to forward alerts to other mailboxes.

4. Bite the bullet and add new recipients to the alert notifications (but keeping TenantAdmins). You can use the [Get-ProtectionAlert](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/get-protectionalert?view=exchange-ps) and [Set-ProtectionAlert](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/set-protectionalert?view=exchange-ps) in SSC PowerShell to make this more manageable. I wasn't able to do this in bulk because it seems these cmdlets don't support piping. But maybe you could script this and run it periodically. Get-ProtectionAlert | Fl Name,NotifyUser returns all alert policies and users who receive notifications. Set-ProtectionAlert <identity> -NotifyUser <list of email addresses>

After doing this initially, you'll have to periodically, determine if new default alert policies are added and update them.  will configure notifications.

HTH

**Comment by markjjo** [comment]
@acraftydev Forget to include in option 2: you can also block the sign-in for the tenant admin account to prevent global admins with FullAccess permissions from signing into the mailbox. You could also hide this mailbox from the global address list in EXO.
