### ISSUE TITLE
SPClaimTypeMapping

### ISSUE THREAD

**Issue by astpc** [MicrosoftDocs/OfficeDocs-Enterprise#67]
Hi,
Great job on this.
I've successfully set this up in Sharepoint 2013 and it seems like only the upn has been successfully mapped.

Is it possible to the following 2 SPClaimTypeMapping and just keep the "name" claim?
$map2 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" -IncomingClaimTypeDisplayName "GivenName" -SameAsIncoming
$map3 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" -IncomingClaimTypeDisplayName "SurName" -SameAsIncoming

Thanks for your help.
Regards,
astpc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f079fa08-284c-3f14-be4a-1f32d5b0e7b9
* Version Independent ID: 707cbeee-d311-d430-6119-e9ae8b8aeae5
* Content: [Using Azure AD for SharePoint Server Authentication](https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication)
* Content Source: [Enterprise/using-azure-ad-for-sharepoint-server-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/using-azure-ad-for-sharepoint-server-authentication.md)
* Service: **o365-solutions**
* Product: **unspecified**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by kaevans** [comment]
@astpc No. SharePoint reserves the name claim for other uses, which is why the UPN claim is mapped instead. The `New-SPTrustedIdentityTokenIssuer` command requires a parameter `IdentifierClaim` that identifies which claim uniquely identifies the user.

**Comment by kaevans** [comment]
@denisebmsft please close

**Comment by AlN3t** [comment]
Thanks Kirk.
Apologies, I had a typo in the question. 
I meant if it is possible to remove the following $map2, $map3 which will reduce the search to 1 claim type instead of 3 in the people picker?
$map2 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" -IncomingClaimTypeDisplayName "GivenName" -SameAsIncoming
$map3 = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname" -IncomingClaimTypeDisplayName "SurName" -SameAsIncoming

Thanks,
Alain
