### ISSUE TITLE
Error re: Azure AD Connect in final section

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Enterprise#675]
This:

> What about hybrid components and Office 365 inter-tenant collaboration?
> On-premises hybrid components, such as an Exchange organization and Azure AD Connect, cannot be split across multiple tenants.

Is true for Exchange, but is NOT true for Azure AD Connect.  For the latter, the answers that (at least I hope) are true, can be found here - https://docs.microsoft.com/en-us/azure/active-directory/hybrid/plan-connect-topologies#multiple-azure-ad-tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41bcfce7-bfcf-f2da-f752-36ac0e497b78
* Version Independent ID: 880faa66-d243-6598-ae24-cf0e4d5a7c16
* Content: [Office 365 inter-tenant collaboration](https://docs.microsoft.com/en-us/office365/enterprise/office-365-inter-tenant-collaboration#points-to-be-aware-of-about-office-365-inter-tenant-collaboration)
* Content Source: [Enterprise/office-365-inter-tenant-collaboration.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-inter-tenant-collaboration.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by msbemba** [comment]
@JeremyTBradshaw Thank you for the feedback. We have made changes to the doc via PR # https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/pull/680

Thanks
Sri

**Comment by JeremyTBradshaw** [comment]
@msbemba Thanks for letting me know and putting in the changes.

**Comment by chrfox** [comment]
HI @JeremyTBradshaw  - Thanks for your comment. I checked with owning PM and confirmed that AAD Connect instances cannot support multiple tenants.  Please see this from the same article  "There's a 1:1 relationship between an Azure AD Connect sync server and an Azure AD tenant. For each Azure AD tenant, you need one Azure AD Connect sync server installation. The Azure AD tenant instances are isolated by design. That is, users in one tenant can't see users in the other tenant. If you want this separation, this is a supported configuration. Otherwise, you should use the single Azure AD tenant model."

**Comment by JeremyTBradshaw** [comment]
@chrfox thanks for the info.  I am in agreement as well.  In hindsight, what I was thinking of is that an AD forest can be split between tenants via multiple AAD Connect instances.  But it seems the topic at hand is specifically for AAD Connect, not Active Directory.

So good catch and sorry to add unnecessary cycles with this one.
