### ISSUE TITLE
Endpoints for Office 365 IP Address and URL are not working

### ISSUE THREAD

**Issue by tianlin-steven-yu** [MicrosoftDocs/OfficeDocs-Enterprise#689]
The endpoint for downloading Office 365 URLs and IP address ranges, as suggested on [office-365-ip-web-service)](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service), stop working. 

First noticed on Jan 27, 2020. The endpoints were working previously. When using web browser, the link will hang and no response is returned. When querying using python request, an error message will be returned: 
`Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'`

List of endpoints that stopped working inlcude:

- https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7

- https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7ebf92c-e478-0f65-0494-97042e974b46
* Version Independent ID: 7e1b9b91-d60d-8665-9a39-2ca77a46b4ce
* Content: [Office 365 IP Address and URL web service](https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service)
* Content Source: [Enterprise/office-365-ip-web-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-ip-web-service.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by kelleyvice-msft** [comment]
I was unable to reproduce the issue; the web service is online. One thing to keep in mind is that you should always generate the clientrequestid GUID on a per-machine basis rather than reusing the example GUID from the document. The web service may stop responding to requests using an example ID. Read this section for more information: https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service#common-parameters

Thanks,
Kelley
