### ISSUE TITLE
Localized ja-jp page means opposite to its English page

### ISSUE THREAD

**Issue by masa-narita** [MicrosoftDocs/OfficeDocs-Enterprise#700]
ja-jp: https://docs.microsoft.com/ja-jp/Office365/Enterprise/moving-data-to-new-datacenter-geos
en-us: https://docs.microsoft.com/en-us/Office365/Enterprise/moving-data-to-new-datacenter-geos

ja-jp:
Microsoft では、サービスの管理と最適化の一環として、時間の経過とともに主要な顧客データを新しいデータセンター geo に移行することはできません。

This text says that Microsoft cannot move Customer Data to new geo, which is incorrect.

en-us:
Taking no action results in Microsoft being able to move your core customer data at rest to your new datacenter geo over time as part of service management and optimization. 

thank you,

**Comment by mypil** [comment]
@masa-narita - Thank you for submitting feedback.

I will get this issue over to the Enterprise writing team for investigation.

Thank you for reporting and making the docs better. Much appreciated.


I made a note to request the team to update this when the work is complete.

**Comment by mypil** [comment]
@officeglobal @tinamcn - Can you please assist with this Translation (Localization) issue?

Thank you.

cc: @kenwith

**Comment by OfficeGlobal** [comment]
Working on a fix

**Comment by OfficeGlobal** [comment]
@masa-narita  the article has been HumanTranslated and published live

@mypil could you please confirm, asterisks are duplicated in source on purpose?
e.g. \*\*\*\*Japan\*\*\*\* instead of \*\*Japan\*\*
it cause troubles for ITNL version, extra \* are visible at live page

PrintScreen from https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/moving-data-to-new-datacenter-geos.md \:
![image](https://user-images.githubusercontent.com/47977325/74525654-dab48480-4f21-11ea-8d16-6dfa6cf3080d.png)

**Comment by mypil** [comment]
@OfficeGlobal - let me check with the author about your query.

@JoeDavies-MSFT @LauraWi - Can you please confirm if the  asterisks are duplicated in source on purpose?  e.g. ****Japan**** instead of **Japan**. It cause troubles for ITNL version, extra * are visible at live page.

Please confirm so we can create a PR on the source file if those extra asterisks need to be removed.

Thank you.

cc: @kenwith

**Comment by masa-narita** [comment]
Thanks team.

I’ve confirmed that the point I mentioned was fixed in the ja-jp page.

Thank you,
Masa

**Comment by LauraWi** [comment]
@mypil 
I think it's a mistake that the asterisks are duplicated. Okay to create a PR to standardize on the more normal double asterisk for bold.

**Comment by mypil** [comment]
@LauraWi - Thanks for your response. I created PR #723 to remove the duplicated asterisks from the table.

@OfficeGlobal - FYI.
