### ISSUE TITLE
Add the endpoints used by Office to get updates (OfficeCDN)

### ISSUE THREAD

**Issue by TheBaban** [MicrosoftDocs/OfficeDocs-Enterprise#776]
In the Optimize URLs list, you should add the endpoints used by Office 365 ProPlus to update, to avoid that payload to comes through the VPN.
The endpoints are documented in the following article:
https://techcommunity.microsoft.com/t5/office-365-blog/configuring-office-365-proplus-updates-for-remote-workers-using/ba-p/1253491

There is 3 endpoints to whitelist:
mrodevicemgr.officeapps.live.com
officecdn.microsoft.com
officecdn.microsoft.com.edgesuite.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83a36fa1-0345-87d0-7fea-cca68bfe1915
* Version Independent ID: 0eaabf4b-4c4d-06d5-b877-56a7657eceaf
* Content: [Implementing VPN split tunnelling for Office 365](https://docs.microsoft.com/en-us/office365/enterprise/office-365-vpn-implement-split-tunnel)
* Content Source: [Enterprise/office-365-vpn-implement-split-tunnel.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/office-365-vpn-implement-split-tunnel.md)
* Service: **o365-administration**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by PaulCollinge** [comment]
The Optimize marked endpoints are very tightly controlled and are designed to allow customers to perform simple and priority driven optimization on endpoints which are very high volume and/or latency sensitive. Endpoints in this category have to meet certain criteria such as a low rate of change, a small, defined set of IPs and so on. Unfortunately the pro-plus update endpoints do not meet the strict criteria of the Optimize endpoints set due to their very nature and thus cannot be included in this category. However, as with any other defined endpoint if your VPN solution can split tunnel it given the information provided for said endpoint, then they can be added as desired.

**Comment by mypil** [comment]
@TheBaban - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by PaulCollinge so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
