### ISSUE TITLE
Navigating directly to a site collection URL causes Too Many Redirects

### ISSUE THREAD

**Issue by Octavie** [MicrosoftDocs/OfficeDocs-Enterprise#84]
Hi,
When navigating to the web application URL it all works just fine, I can log in and see my home page. However, when I first directly navigate to a site collection URL within the same web application, I get the error Cannot Reach Page. When I watch the Network activity with the F12 Developer tools, I see a lot redirections:
1. Site Collection URL - 302
2. Site Collection URL/_layouts/15/authentication.aspx - 302
3. web app URL /_trust - 302
4. Site Collection URL/_layouts/15/authentication.aspx - 302
5. web app URL /_trust - 302
6. Site Collection URL/_layouts/15/authentication.aspx - 302
etc..

Any thoughts why this is happening? No HNSC, all PathBased Site Collections...

**Comment by denisebmsft** [comment]
Hello Octavie,

MSFTTracyP's has a comment/question for you:

This is likely be because you’re redirecting authentication from on-premises to Azure’s login page. My question is, do you get to the login page? It sounds like you do when you use the web app configured for Azure authentication?

**Comment by Octavie** [comment]
Hi Denise,

I have SharePoint 2016 installed in Azure VMs and used this article (https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication) to integrate with Azure AD.

We have one web application configured with SSL and a couple of path based site collections.
Navigating to the web application URL (root site collection) is just fine.
Navigating to a site collection URL causes the too many redirects.

I am looking for something to solve this behavior. Don't know what is causing this.

grtz,
Octavie

**Comment by MSFTTracyP** [comment]
Thanks for letting me know that level of detail, seeing as it really helps me get context for the problem. A couple more scoping questions:

- When you go to the site collection URL and get too many redirects, how many in total?
- What does the user see on the screen during these redirects?
- Do you ever get to the site collection page? Or does it always error out? (What do you see?)
- What happens if you go to the root site collection, first, and then use the same browser window and the same tab, to go to the site collection URL? Does this work or error out?

I'm asking this in case a workaround will work for your users, Octavie. Please let me know when you can. My feeling on this is because you've got to set a trust to a specific URL in the Azure Enterprise Application, the config is going to need the sign-on URL (which is the one I assume you're using to go to the root application). But I'm probably getting ahead of myself. Let's iron out the questions above first.

Thanks!

**Comment by Octavie** [comment]
Hi good morning,
I have asked Vincent (colleague) to join this conversation, as he has more specific answers for you than I have. I do not have access to the SP2016 VMs all the time. He has. :)

1) How many redirects? As far as I can remember, at least 5 times.
2) The user doesn't see anything but the loading indicator. We were expecting a login screen, but after a few seconds we see the error Could not find page (or something like that).
3) No, we don't. Yes always.

4) Maybe Vincent can tell you more about this scenario.


grtz,
Octavie

**Comment by VinceWeir** [comment]
Hi all,
Thanks for letting me join this conversation.
Going to Url "/_trust/default.aspx" root site collection and opening a path based site collection on a new tab works fine.

**Comment by denisebmsft** [comment]
Hello! 

Octavie, if you are still having trouble, you will want to open a support ticket.
