### ISSUE TITLE
CSV Requires huge mass of optional data?

### ISSUE THREAD

**Issue by HarmlessDave** [MicrosoftDocs/OfficeDocs-Enterprise#849]
When creating manually, only 3 columns are needed: email, first name, last name.  Unless there are undocumented methods, import from CSV requires creating all 15 columns or leaving them blank. Blank is fine for most fields but the display name should come from first and last name by default.  Either the documentation is incomplete or the feature can be improved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 599047e6-0801-134f-25d7-8368e1bd3de5
* Version Independent ID: 55e3397b-af44-7135-7820-1a772f9e0e19
* Content: [Add several users at the same time to Office 365 - Admin Help](https://docs.microsoft.com/en-us/office365/enterprise/add-several-users-at-the-same-time#feedback)
* Content Source: [Enterprise/add-several-users-at-the-same-time.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/add-several-users-at-the-same-time.md)
* Service: **o365-administration**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by msbemba** [comment]
@HarmlessDave  Thank you for your feedback. The optional settings are available while creating a user manually. The Customer's who don't need it can leave it blank but those who want the data updated will find it useful.

For the Display name, you are right that most of the users use the default (First + Last name), But there is an option to edit the display name even when you create manually. So, There are the customers who use a different display name instead of First and last name like Admin, etc or some who have a long name would want to cut short it while it is displayed.

Hope this helps!

Thanks
Sri

**Comment by mypil** [comment]
@HarmlessDave - Thank you for submitting feedback.

From our understanding, the issue you raised has been answered by @msbemba so we will close this issue.



Thank you for your contribution to make the docs better! Much appreciated!
